# Supabase configuration for Zaza Dance App

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54322
external_url = "http://localhost:54322"
jwt_expiry = 3600
refresh_token_rotation_enabled = true
secure_password_change_enabled = true
enable_manual_linking = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[auth.sms]
enable_signup = false

[db]
port = 54323
shadow_port = 54324
major_version = 15

[storage]
enabled = true
port = 54325
file_size_limit = "100MB"
image_transformation_enabled = true

[inbucket]
enabled = true
port = 54326
smtp_port = 54327
pop3_port = 54328

[realtime]
enabled = true
port = 54329
ip_version = "ipv4"

[studio]
enabled = true
port = 54330
api_url = "http://localhost"

[functions]
verify_jwt = false