[build]
  base = "."
  command = '''
    # Install Flutter
    if [ ! -d "/opt/build/cache/flutter" ]; then
      echo "Installing Flutter..."
      cd /opt/build/cache
      git clone https://github.com/flutter/flutter.git -b stable --depth 1
      export PATH="$PATH:/opt/build/cache/flutter/bin"
      flutter doctor
      flutter precache --web
    else
      echo "Flutter already cached"
      export PATH="$PATH:/opt/build/cache/flutter/bin"
    fi
    
    # Build the Flutter web app
    cd /opt/build/repo
    flutter build web --base-href /
  '''
  publish = "build/web"

[build.environment]
  FLUTTER_WEB = "true"
  PATH = "${PATH}:/opt/build/cache/flutter/bin"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"