name: zaza_dance
description: "אפליקציית זזה דאנס - בית דיגיטלי לקהילת חוג ההיפ הופ"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # Core packages
  go_router: ^14.8.1
  riverpod: ^2.5.0
  flutter_riverpod: ^2.5.0
  google_fonts: ^6.0.0
  cupertino_icons: ^1.0.8
  
  # Supabase integration
  supabase_flutter: ^2.6.0
  
  # UI and animations
  flutter_animate: ^4.5.2
  flutter_glow: ^0.3.2
  
  # Video and media
  video_player: ^2.9.2
  youtube_player_flutter: ^9.1.0
  cached_network_image: ^3.4.1
  image_picker: ^1.2.0
  flutter_image_compress: ^2.3.0
  
  # Utilities
  permission_handler: ^12.0.1
  share_plus: ^11.1.0
  url_launcher: ^6.3.1
  intl: ^0.20.2
  app_links: ^6.3.2
  shared_preferences: ^2.3.2
  http: ^1.2.2
  
  # Cache and Performance
  flutter_cache_manager: ^3.4.1
  path_provider: ^2.1.4
  
  # Notifications - עדכון לגרסה חדשה
  flutter_local_notifications: ^19.4.0
  timezone: ^0.10.1
  
  # Device Info
  device_info_plus: ^11.1.0
  
  # State Management and Models
  equatable: ^2.0.5
  file_picker: ^10.3.1
  
  # Admin panel dependencies
  json_annotation: ^4.9.0
  fl_chart: ^0.69.1
  flutter_dropzone: ^4.0.3
  mime: ^1.0.6
  image: ^4.2.0
  path: ^1.9.0
  uuid: ^4.5.1
  video_thumbnail: ^0.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.13
  json_serializable: ^6.8.0

dependency_overrides:
  # Ensure compatible versions for Android Gradle 8.12
  flutter_local_notifications: ^19.4.0
  timezone: ^0.10.1

flutter:
  uses-material-design: true
  
  # Assets
  assets:
    - assets/images/
    - assets/videos/
  
  # Note: Google Fonts Assistant will be downloaded automatically
  # No need for local font files as google_fonts package handles this