name: zaza_dance
description: "אפליקציית זזה דאנס - בית דיגיטלי לקהילת חוג ההיפ הופ"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # Supabase integration
  supabase_flutter: ^2.6.0
  
  # UI and animations
  flutter_animate: ^4.5.2
  flutter_glow: ^0.3.2
  google_fonts: ^6.2.1
  
  # Video and media
  video_player: ^2.9.2
  cached_network_image: ^3.4.1
  image_picker: ^1.1.2
  
  # State management and navigation
  go_router: ^16.1.0
  riverpod: ^2.6.1
  flutter_riverpod: ^2.6.1
  
  # Utilities
  permission_handler: ^12.0.1
  share_plus: ^11.1.0
  url_launcher: ^6.3.1
  intl: ^0.20.2
  
  # Cache and Performance
  flutter_cache_manager: ^3.4.1
  path_provider: ^2.1.4
  
  # Notifications
  flutter_local_notifications: ^17.2.3
  
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  
  # Assets
  assets:
    - assets/images/
    - assets/videos/
    
